export const ROBLOX_SECURITY_TOKENS_ENV_PREFIX = "ROBLOX_SECURITY_TOKENS_";
export const IPINFO_ACCESS_TOKEN_ENV_KEY = "IPINFO_ACCESS_TOKEN";
export const PRIVATE_ACCESS_COOKIE_ENV_KEY =
	"ROBLOX_PRIVATE_ACCESS_SECURITY_TOKEN";

export const ROBLOX_USER_AGENT =
	"Roblox/WinInet RobloxApp/0 (GlobalDist; RobloxDirectDownload)";
